### ISSUE TITLE
Issue with custom expand renderer

### ISSUE THREAD

**Issue by corinadev** [damiengarbarino/dojo-calendar#102]
After upgrading dojo, at the initialization step of the calendar, I got the following error: `Uncaught TypeError: Cannot read property 'ownerDocument' of null`.

After investigating, I found that the `_getCellAt` method from `MatrixView.js` is called with an undefined `columnIndex`, that I traced back to the `_layoutExpandRenderers` method in the `ColumnViewSecondaySheet.js` file, where the column is assigned an undefined value: `var col = this._expandedRowCol;`.

```

        _layoutExpandRenderers: function(index, hasHiddenItems, hiddenItems) {
            if(!this.expandRenderer || this._expandedRowCol == -1) {
                return;
            }
            var h = domGeometry.getMarginBox(this.domNode).h;
            if(this._defaultHeight == -1) {
                this._defaultHeight = h;
            }

            if(this._defaultHeight != -1 && this._defaultHeight != h && h >= this._getExpandedHeight() ||
                this._expandedRowCol !== undefined && this._expandedRowCol !== -1) {
                var col = this._expandedRowCol; // => this assigned undefined to col, which is then passed to the _getCellAt method
                if(col >= this.renderData.columnCount) {
                    col = 0;
                }
                this._layoutExpandRendererImpl(0, col, null, true);
            } else {
                this.inherited(arguments);
            }
        },
```

From what I understand, `undefined` is the default value for `_expandedRowCol`, however in the method many of the checks are against `-1`. My assumption is that this method shoudn't even be called in my case, since no column is expanded, but it gets executed because the check in the first line only checks for -1:

```
if(!this.expandRenderer || this._expandedRowCol == -1) {
     return;
}
```

**Comment by monnu** [comment]
Hi I am suffering from the same error.   TypeError: Cannot read property 'ownerDocument' of null.
But I am unable to recognize what value its taking null because the file in which its showing the error is generated file.Could you please guide me how to recognize what value its taking null.I

**Comment by monnu** [comment]
var visualTreeTab = new ContentPane ({
	        	id: "visualTreeTab",
	        	title: "<s:message code="visualTree.header"></s:message>",
	        	content: "visualTree Details..."}, "visualTreeTab");
	       
	           contentTabs.addChild(visualTreeTab);    

After removing this   "content: "visualTree Details..."  line from the code I am getting that error.
Is it related to some dojo content pane .How to recognize where its showing the null value because its showing in some generated file.
Please guide me.
