### ISSUE TITLE
Error in demo page

### ISSUE THREAD

**Issue by yurychika** [damiengarbarino/dojo-calendar#110]
Demo here: http://demos.dojotoolkit.org/demos/calendar/

1. click any event
2. press *ENTER* button
3. error occurs in console

![image](https://cloud.githubusercontent.com/assets/1291912/8893655/1a4aaafa-33cc-11e5-8881-1be087819eab.png)

**Comment by damiengarbarino** [comment]
Fixed in master and dojo1.10
Thanks for the report!

**Comment by yurychika** [comment]
@damiengarbarino thanks for the effort!
