### ISSUE TITLE
always respect dateClassObj when constructing new date objects

### ISSUE THREAD

**Issue by gerpres** [damiengarbarino/dojo-calendar#116]
hi,
I already reported a bug at

https://bugs.dojotoolkit.org/ticket/18796

in the latest dojo-release, dojox/calendar/ViewBase._setupDayRefresh doesn't use newDate() to construct a date-instance.
is it possible to fix this for the upcomming 1.11 release?

**Comment by dylans** [comment]
The revised dojox/calendar version has been updated in Dojo master and 1.11.x. 1.10 was using an earlier version so I have not updated it, but will do so if someone has time to test.
