### ISSUE TITLE
when a calendar item is created and then updated (via the store), the item is duplicated on the calendar

### ISSUE THREAD

**Issue by ezp-matt** [damiengarbarino/dojo-calendar#8]
I've created a testcase for this issue.  In the testcase, I have one event that is pre-defined in the store ("Item #1").  Once the page is loaded, the dojo.ready() function updates Item #2 (with a new summary and start/end time), and then creates a new item ("Item #2"), and then updates that item (with a new summary and start/end time).  You'll see that the first item updates fine, but the second item get duplicated.  What's interesting, though, is that if you look at calendar_store._arrayOfAllItems after the page is loaded, there's only two items in the store.. so they're just getting duplicated on the calendar, the store itself is working fine.

I tried to track down this bug to fix it myself but couldn't seem to find the source of it.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link rel="stylesheet" type="text/css" href="dijit/themes/claro/document.css" />
<link rel="stylesheet" type="text/css" href="dijit/themes/claro/claro.css" />
<link rel="stylesheet" type="text/css" href="dojox/calendar/themes/claro/Calendar.css" />
<script src="dojo/dojo.js" type="text/javascript" data-dojo-config="parseOnLoad: true"></script>

<script type="text/javascript">
require([
    "dojo/ready",
    "dojo/data/ItemFileWriteStore",
    "dojo/store/DataStore",
    "dojo/store/Observable",
    "dojox/calendar/Calendar"
], function(ready) {
    ready(function() {
        // update event #1
        calendar_dataStore.put({'id':1,'summary':'Item #1 Update','startTime':'2012-03-06T12:00:00','endTime':'2012-03-06T16:00:00'});
        // create event #2
        calendar_dataStore.put({'id':2,'summary':'Item #2','startTime':'2012-03-07T10:00:00','endTime':'2012-03-07T14:00:00'});
        // update event #2
        calendar_dataStore.put({'id':2,'summary':'Item #2 Update','startTime':'2012-03-07T12:00:00','endTime':'2012-03-07T16:00:00'});
    });
});

// predefined data
var calendarData = {
    'identifier':'id',
    'numRows':1,
    'items':[
        {'id':1,'summary':'Item #1','startTime':'2012-03-06T10:00:00','endTime':'2012-03-06T14:00:00'}
    ]
}
</script>

</head>

<body class="claro">

<div data-dojo-type="dojo.data.ItemFileWriteStore" data-dojo-id="calendar_store" data-dojo-props="data:calendarData"></div>
<div data-dojo-type="dojo.store.DataStore" data-dojo-id="calendar_dataStore" store="calendar_store"></div>
<div data-dojo-id="calendar" data-dojo-type="dojox.calendar.Calendar" store="dojo.store.Observable(calendar_dataStore)"></div>

</body>
</html>
```

**Comment by mehtabhaumik** [comment]
I have a issue.

I have Memory/JsonRest store set up with the calendar. What happening is, that if I switch from Monthly view to Weekly view, the calendar shows the events for current date and future dates on weekly view but it doesn't show events for past dates on weekly view(shows on monthly view though). I tried different approach but failed. Could you pls help me in this?
